In [1]:
import torch
from vanilla_rnn import RNN

In [2]:
VOCAB_SIZE = 30
INPUT_SIZE = 10
HIDDEN_SIZE = 20

In [3]:
rnn_lm = RNN(input_size=INPUT_SIZE, hidden_size=HIDDEN_SIZE, output_size=VOCAB_SIZE)

In [4]:
rnn_lm

RNN(
  (i2h): Linear(in_features=30, out_features=20, bias=True)
  (i2o): Linear(in_features=20, out_features=30, bias=True)
  (tanh): Tanh()
  (softmax): Softmax(dim=1)
)

In [5]:
input_tensor = torch.randn(1, INPUT_SIZE)
input_tensor

tensor([[ 0.9075,  0.3500, -0.8807,  0.0482, -0.5602,  0.4095, -0.7242,  0.2670,
         -0.6889, -0.0275]])

In [6]:
hidden = rnn_lm.initHidden()
hidden

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
output, next_hidden = rnn_lm(input_tensor, hidden)

In [8]:
output

tensor([[0.0522, 0.0266, 0.0279, 0.0460, 0.0326, 0.0292, 0.0276, 0.0357, 0.0267,
         0.0316, 0.0386, 0.0291, 0.0295, 0.0355, 0.0301, 0.0345, 0.0329, 0.0343,
         0.0355, 0.0307, 0.0285, 0.0331, 0.0316, 0.0418, 0.0305, 0.0364, 0.0345,
         0.0322, 0.0365, 0.0281]], grad_fn=<SoftmaxBackward0>)

In [ ]:
next_hidden